file(GLOB CORAL_TEST_SOURCES CONFIGURE_DEPENDS
  "${CMAKE_CURRENT_SOURCE_DIR}/*.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/*.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/*.cxx"
)

list(SORT CORAL_TEST_SOURCES)

find_package(Threads REQUIRED)

set(CORAL_TEST_OUTPUT_DIRECTORY "${PROJECT_BINARY_DIR}/bin/tests")

enable_testing()

foreach(TEST_SOURCE IN LISTS CORAL_TEST_SOURCES)
  get_filename_component(TEST_NAME "${TEST_SOURCE}" NAME_WE)
  add_executable("${TEST_NAME}" "${TEST_SOURCE}")
  
  target_link_libraries("${TEST_NAME}" PRIVATE coral Threads::Threads)

  set_target_properties("${TEST_NAME}" PROPERTIES
    RUNTIME_OUTPUT_DIRECTORY "${CORAL_TEST_OUTPUT_DIRECTORY}")

  set_target_properties("${TEST_NAME}" PROPERTIES
    RUNTIME_OUTPUT_DIRECTORY "${CORAL_TEST_OUTPUT_DIRECTORY}"
    RUNTIME_OUTPUT_DIRECTORY_DEBUG "${CORAL_TEST_OUTPUT_DIRECTORY}"
    RUNTIME_OUTPUT_DIRECTORY_RELEASE "${CORAL_TEST_OUTPUT_DIRECTORY}"
    RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO "${CORAL_TEST_OUTPUT_DIRECTORY}"
    RUNTIME_OUTPUT_DIRECTORY_MINSIZEREL "${CORAL_TEST_OUTPUT_DIRECTORY}"
  )

  add_test(NAME "${TEST_NAME}" COMMAND "${TEST_NAME}")
endforeach()
